claims:
  static:
    models:
      - llama3-70b
      - mixtral-8x7b
    rate_limit: 50
    tier: standard
    exp_hours: 3       # Token expires after 3 hours
  dynamic:
    quota:
      type: function
      module: claims.quota
      function: get_remaining_quota
      args:
        user_id: "{user_id}"
    model_access:
      type: function
      module: claims.access
      function: check_model_access
      args:
        api_key_id: "{api_key_id}"
