# Sample users file for file-based authentication
# In production, use a secure password hashing method like bcrypt
# Current passwords are SHA-256 hashed
# Example entry for user 'admin' with password 'password'

admin:
  password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  # SHA-256 for 'password'
  name: Administrator
  email: admin@example.com
  groups:
    - administrators
  roles:
    - admin
    - user

user1:
  password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  # SHA-256 for 'password'
  name: Regular User
  email: user1@example.com
  groups:
    - users
  roles:
    - user

testuser:
  password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  # SHA-256 for 'password'
  name: Regular User
  email: user1@example.com
  groups:
    - users
  roles:
    - user
